### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by alayek** [alayek/backend-challenges#1]
Create a README describing what this is for, what type of problems we keep, and where to find problem for each of the languages.

**Comment by alayek** [comment]
@koustuvsinha please review. I added a small README.

**Comment by koustuvsinha** [comment]
its ok. add a license at the end

**Comment by alayek** [comment]
Creative Commons?

**Comment by koustuvsinha** [comment]
yes. the same one FCC uses :smile:

**Comment by alayek** [comment]
Ok, they use BSD-3. I added the same,but me as owner.

When I transfer ownership to FCC, we would update this to reflect FCC as owner.
