### ISSUE TITLE
Moving tests to Mocha

### ISSUE THREAD

**Issue by raisedadead** [alayek/backend-challenges#24]
Travis-CI is currently broken as seen in #23 even when the scripts are throwing error. This is because the current script is not handling the error and letting travis know of this. This is leading to false positives

Moving to mocha should help us resolve this cleanly.

To best of my knowledge Free Code Camp uses its own logic instead of mocha but I still propose its okay to have mocha tests, which are fairly simple and fast to implement.

Working on this on the branch https://github.com/alayek/backend-challenges/tree/travis-ci

Feel free to pitch in.

**Comment by alayek** [comment]
But we are keeping Mocha only for the REPL testing right? As in, not to test language specific module. Like testing a Python module using Python test runners?

**Comment by raisedadead** [comment]
Not sure if I understand clearly. 

But here is the deal, to validate the challenges while merging changes and upgrades we will use Travis, for that we will hook up `npm run` scripts.

These will basically execute test cases against the challenges to test their validity.

This will involve calls to REPL.it API, as it was earlier.

Mocha testing library is simple to implement and should help in overcoming the issues witg Travis.

**Comment by alayek** [comment]
See, there are two phases of testing we do in Travis.
- Install the language for the problem, use its native test runner to run the unit test.
- Install Node JS and REPL npm module. We can use that to send the solution to REPL with the token and execute it there and get the return value.

If both passes, solution is correct. If first one passes second one fails - solution is correct but REPL is not properly set up. If first one fails and second one passes - REPL is executing something fluff, and not the actual test.

You want to use Mocha to test the response from the second part, right?

**Comment by raisedadead** [comment]
Okay, much clear now. Yeah the intent is to test the second part using Mocha.

**Comment by raisedadead** [comment]
Sorry, Just cleaning up my issues queue. Thanks for your help & support.
