### ISSUE TITLE
Integrate repo with gitter

### ISSUE THREAD

**Issue by alayek** [alayek/backend-challenges#3]
We need to integrate this repo with the gitter chatroom.

**Comment by koustuvsinha** [comment]
i think only repo owners can set the webhooks in settings. can you check @alayek ?

**Comment by alayek** [comment]
Ok checking...

**Comment by alayek** [comment]
Integrated and added a label in README. Please check...

**Comment by koustuvsinha** [comment]
yes, integration done :+1:
