### ISSUE TITLE
Create a simple test runner using locust

### ISSUE THREAD

**Issue by koustuvsinha** [alayek/backend-challenges#6]
Using [locust.io](http://docs.locust.io/), create a simple `test-runner.py` to emulate a hello world.

**Comment by koustuvsinha** [comment]
tested with ReplitClient.js, which is just working in the browser. so would need a better way to test, maybe using phantomJS, as locust is good to stress test individual pages, but not the concurrent websocket connection within the page.

**Comment by alayek** [comment]
@koustuvsinha check in the gitter room. I think Stefan was trying something like that, but couldn't invoke a JaveScript function from within a script tag. The error was that the function name was not being recognized.

I asked in Phantom JS IRC, but not much response. Take a look. If you are unable to find a remedy, I would file an issue with Phantom JS repo.
